server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

spring:
  application:
    name: ncc-formation-backend
  
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:nccdb}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
  
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:true}
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:create-drop}
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
        dialect: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}
  
  sql:
    init:
      mode: never

main:
  allow-circular-references: true
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT Configuration
jwt:
  secret: ncc-formation-secret-key-2024-very-secure
  expiration: 86400000 # 24 hours

# CORS Configuration
cors:
  allowed-origins: 
    - http://localhost:4200
    - https://nccformation.netlify.app
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"

# Swagger Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Logging
logging:
  level:
    com.nccformation: DEBUG
    org.springframework.security: DEBUG